### ISSUE TITLE
Are you interested in pull requests?

### ISSUE THREAD

**Issue by picrap** [axelheer/nein-math#1]
Hi,

I like your project and would like to add two improvements:
- .NET 4.0 compat (which is one line change)
- Conversion to and from `byte[]` (in order to do RSA computation from external sources)
I'm already working on these so let me know if you accept pull requests.

Regards.
Pascal.

**Comment by axelheer** [comment]
Sure, pull requests are welcome.

Did you noticed, that the class `BitIntegerConverter` has already `byte[]` conversions?

**Comment by picrap** [comment]
OK, great, then! So we only need a 4.0 compatibility
